name: Dependencies and Code Security Scan

on:
  push:
    branches:
      - main
    paths:
      - 'apisix-tenant-provisioner/**'

  pull_request:
    branches:
      - main
    paths:
      - 'apisix-tenant-provisioner/**'

jobs:
  # Job 1: Existing Trivy Scan
  trivy-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Run Trivy Scanner
        uses: aquasecurity/trivy-action@master
        with:
          format: 'json'
          output: 'trivy-report.json'
          scan-ref: './apisix-tenant-provisioner'
          scan-type: 'fs'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          exit-code: '0'  # Change to 0 so pipeline doesn't stop before SonarQube runs

      - name: Upload the trivy report as an artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Security-scan-report
          path: trivy-report.json

  # Job 2: New SonarQube Scan Added
  sonarqube-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones disabled for complete analysis

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectBaseDir=apisix-tenant-provisioner
